default:
  models:
    Output: read
    PromptExecution: read
    PromptSection: read
    Prompt: read
    InputItem: read
    InputType: read
    Project: read
    IntelligenceCredential: read
    InvitationKey: read
    Team: read
    Membership:
      - read
      - search
    Platform::Application: read
    Webhooks::Outgoing::Endpoint: manage
    Webhooks::Outgoing::Event: read
    Webhooks::Outgoing::Delivery: read
    Webhooks::Outgoing::DeliveryAttempt: read
    Invitation:
      - read
      - create
      - destroy

editor:
  models:
    Scaffolding::CompletelyConcrete::TangibleThing: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept:
      - read
      - update

admin:
  includes:
    - editor
  manageable_roles:
    - admin
    - editor
  models:
    Output: manage
    PromptExecution: manage
    PromptSection: manage
    Prompt: manage
    InputItem: manage
    InputType: manage
    Project: manage
    IntelligenceCredential: manage
    InvitationKey: manage
    Team: manage
    Membership: manage
    Scaffolding::AbsolutelyAbstract::CreativeConcept: manage
    Platform::Application: manage
